Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-10, with the labels that each got.

#1748 Express accuracy outside of Currency conversion
  core/order.go
  repo/currency.go
  repo/currency_test.go
Labels: ethereum

#1753 Fixes needed after listing schema changes
  core/confirmation.go
  core/order.go
  qa/complete_moderated_online.py
  qa/manage_crypto_listings.py
  qa/testdata/listing.json
  qa/testdata/listing_crypto.json
  repo/listing.go
Labels: ethereum

#1751 Use currency code in profile instead of String() output
  core/profile.go
Labels: ethereum

#1724 Increased verbose logging for orders to help track down issues
  core/net.go
  net/service/handlers.go
  net/service/messagesender.go
  net/service/service.go
Labels: needs review

#1758 Update to use protobuf Listing.Item.Sku.BigQuantity
  api/jsonapi_test.go
  core/listings.go
  core/signed_listings.go
  core/signed_listings_test.go
  pb/contracts.pb.go
  pb/protos/contracts.proto
  qa/manage_crypto_listings.py
  qa/runtests.sh
  qa/testdata/eth_listing_crypto.json
  qa/testdata/listing_crypto.json
  repo/listing.go
  repo/migrations/Migration026_test.go
  test/factory/listing.go
Labels: ethereum, feature, 🔍 readyForReview

#1763 Fix eth qa tests
  net/service/handlers.go
  qa/eth_complete_disputed.py
  qa/eth_dispute_close_vendor.py
  qa/eth_escrow_release_after_timeout.py
  qa/eth_purchase_crypto_listing.py
  qa/testdata/eth_listing.json
  qa/testdata/eth_listing_crypto.json
  repo/sale_record.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: ethereum, 🔍 readyForReview

#1762 Add conversions functions for backwards compatibility
  core/completion.go
  core/confirmation.go
  core/disputes.go
  core/fulfillment.go
  core/refunds.go
  core/utils.go
  net/service/handlers.go
  repo/buyer_order.go
  repo/buyer_order_test.go
  repo/dispute.go
  repo/dispute_case_record.go
  repo/dispute_resolution.go
  repo/dispute_resolution_test.go
  repo/dispute_test.go
  repo/order_confirmation.go
  repo/order_confirmation_test.go
  repo/order_fulfillment.go
  repo/order_fulfillment_test.go
  repo/refund.go
  repo/refund_test.go
Labels: ethereum, 🔍 readyForReview

#1773 Express repo.Listing.CryptoDivisibility as exponential value
  repo/listing.go
  repo/listing_test.go
Labels: ethereum

#1776 Fix net.service shutdown panic
  net/service/service.go
  qa/testdata/digital.json
Labels: :rocket: :no_entry_sign:, ethereum, 🔍 readyForReview

#1775 Fix bugs handling big inventory
  api/jsonapi.go
  api/jsonapi_data_test.go
  core/errors.go
  core/inventory.go
  core/listings.go
  core/order.go
  core/signed_listings.go
  core/signed_listings_test.go
  qa/manage_crypto_listings.py
  qa/market_price_modifier.py
  qa/testdata/listing_crypto.json
  repo/datastore.go
  repo/db/inventory.go
  repo/db/inventory_test.go
  repo/listing.go
  wallet/listeners/transaction_listener.go
Labels: :rocket: :no_entry_sign:, ethereum, 🔍 readyForReview

#1778 Revert back to 'coinType' key in listing index
  repo/currency_definition.go
  repo/currency_definition_test.go
  repo/listing.go
  repo/listing_index.go
Labels: :rocket: :no_entry_sign:, ethereum, 🚧 in progress

#1774 Add blocktime to currency definition
  api/jsonapi_data_test.go
  core/completion.go
  core/disputes.go
  repo/currency_definition.go
  repo/currency_definition_test.go
  test/factory/currency.go
Labels: :rocket: :no_entry_sign:, ethereum, 🚧 in progress

#1777 check txn receipt for transfer
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: :rocket: :no_entry_sign:, ethereum, 🚧 in progress

#1788 Move the contract listings to factory pattern
  core/signed_listings_test.go
  test/contracts/signed_listings_1_invalid.json
  test/factory/fixtures/listings/v5-signed-physical-good-2.json
Labels: ethereum, 🔍 readyForReview

#1793 Allow TxMetadata to be missing when recieving a wallet tx
  wallet/listeners/wallet_listener.go
Labels: bug, ethereum

#1795 Use correct currency code when converting crypto prices
  core/order.go
  core/order_test.go
Labels: ethereum, 🔍 readyForReview

#1816 IPNS improvements to prevent panic
  api/jsonapi.go
  cmd/start.go
  core/core.go
  core/net.go
  core/profile.go
  ipfs/config.go
  ipfs/pubsub.go
  ipfs/resolve.go
  mobile/node.go
  net/retriever/retriever.go
  net/service/handlers.go
  repo/migration.go
  repo/migrations/Migration026.go
  repo/migrations/Migration026_test.go
  repo/migrations/log.go
Labels: 🔍 readyForReview

#1828 (#1814) Upgrade repo.PurchaseData to use bigQuantity
  core/order.go
  qa/testdata/order_crypto.json
  qa/testdata/order_digital.json
  qa/testdata/order_direct.json
  qa/testdata/order_direct_too_much_quantity.json
  repo/listing.go
Labels: ethereum, 🔍 readyForReview

#1822 (#1499) Fix double amount in payment record
  core/utils.go
Labels: ethereum, 🔍 readyForReview

#1825 (#1820) Support unknown currencies in market price lookup
  core/order.go
  repo/currency_definition.go
Labels: bug, ethereum, 🔍 readyForReview

#1827 (#1823) Fix PATCH /ob/profile to update profile.Currencies
  api/jsonapi_test.go
  core/profile.go
Labels: bug, ethereum, 🔍 readyForReview

#1831 (#1799) Set default escrow timeout hours on listing create
  repo/listing.go
Labels: ethereum, 🔍 readyForReview

#1832 (#1787) Fix bug setting inventory on own listings
  core/listings.go
Labels: ethereum, 🔍 readyForReview

#1837 (#1821) Improve/protect PATCH /ob/settings
  api/jsonapi.go
  api/jsonapi_helpers_test.go
  api/jsonapi_test.go
  core/moderation.go
  test/factory/settings.go
Labels: ethereum
