Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-02, with the labels that each got.

#1455 Add withTimeout to Chat and Offline Messages
  core/core.go
  core/net.go
Labels: changes requested, enhancement

#1423 Bulk Update Currencies for Listings
  api/endpoints.go
  api/jsonapi.go
  api/jsonapi_data_test.go
  api/jsonapi_test.go
  core/listings.go
  core/signed_listings.go
  core/signed_listings_test.go
  test/contracts/signed_listings_1.json
  test/contracts/signed_listings_1_invalid.json
Labels: enhancement, needs rebase, needs review

#1345 Sign Verify Content with IPFS Key
  api/endpoints.go
  api/jsonapi.go
  api/jsonapi_data_test.go
  api/jsonapi_test.go
Labels: enhancement, needs review

#1342 Refactor order.go
  core/order.go
  qa/purchase_direct_offline.py
  qa/purchase_moderated_offline.py
Labels: enhancement, needs review

#1313 [docs] Note for new golang hackers
  docs/install-linux.md
  docs/install-osx.md
Labels: needs rebase

#1465 Improve Exchange Rates
  .travis.yml
  Dockerfile.dev
  api/jsonapi.go
  core/disputes.go
  core/order.go
  core/utils.go
  repo/currency.go
  repo/currency_definition.go
  repo/currency_definition_test.go
  repo/currency_definitions_validity_test.go
  repo/currency_test.go
  repo/db/cases.go
  repo/db/cases_test.go
  repo/db/purchases.go
  repo/db/purchases_test.go
  repo/db/sales.go
  repo/db/sales_test.go
  test/factory/currency.go
Labels: needs review
