Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-03, with the labels that each got.

#1495 IPFS repo migration 6 -> 7
  qa/smtp_notification.py
  qa/testdata/digital.json
  qa/testdata/listing.json
  qa/testdata/listing_crypto.json
  repo/init.go
  repo/migration.go
  repo/migrations/Migration020.go
  repo/migrations/Migration020_test.go
  repo/migrations/helpers/Migration020/record.pb.go
  repo/migrations/helpers/Migration020/record.proto
Labels: bug, needs review

#1510 Sign/Verify message fixes
  api/jsonapi.go
  api/jsonapi_data_test.go
  api/jsonapi_test.go
Labels: bug

#1523 Provide -t flag for mobile cmd to start in testnet mode
  mobile/cmd/main.go
Labels: enhancement
