Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-09, with the labels that each got.

#1715 Support legacy (v4) listing index and other refactorings
  api/jsonapi.go
  api/jsonapi_data_test.go
  api/jsonapi_test.go
  cmd/convert.go
  core/disputes.go
  core/listings.go
  core/listings_test.go
  core/moderation.go
  core/order.go
  core/order_test.go
  core/profile.go
  core/spend.go
  core/utils.go
  repo/currency.go
  repo/currency_definition.go
  repo/currency_definition_test.go
  repo/currency_definitions_validity_test.go
  repo/currency_test.go
  repo/db/cases.go
  repo/db/purchases.go
  repo/db/sales.go
  repo/listing.go
  repo/listing_index.go
  repo/listing_index_test.go
  repo/listing_test.go
  test/factory/currency.go
  test/factory/fixtures/listings/v4-index.json
  test/factory/fixtures/listings/v5-index.json
  wallet/status.go
Labels: ethereum

#1720 Enable v4 listing index support in API
  api/jsonapi.go
  core/core.go
  core/listings.go
  ipfs/pin.go
  repo/currency_definition.go
  repo/listing_index.go
  repo/listing_index_test.go
  repo/migrations/Migration026.go
  repo/migrations/Migration027_test.go
  repo/migrations/Migration028.go
  test/factory/fixtures/listings/v5-index.json
  wallet/listeners/transaction_listener.go
  wallet/listeners/wallet_listener.go
  wallet/resync/resync_manager.go
Labels: bug

#1733 Fix 1418 and 1431
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/client.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: :rocket: :no_entry_sign:, ethereum
