Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-12, with the labels that each got.

#1883 (#1880) Remove validation for non-nil mod info
  repo/profile.go
  repo/profile_test.go
Labels: ethereum, 🔍 readyForReview

#1885 (#1877) Add PayoutCurrency to dispute payouts
  core/disputes.go
Labels: bug, ethereum, 🔍 readyForReview

#1887 (#1862) Re-enable missing API endpoints for LTC pricing
  vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go
Labels: bug, ethereum, 🔍 readyForReview

#1888 (#1840) Show negative values for outgoing eth transactions
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: ethereum, 🔍 readyForReview

#1912 (#1881) Check for non nil moderator fixed fee amount
  core/profile.go
  repo/profile.go
  repo/profile_test.go
  test/factory/profile.go
Labels: ethereum

#1905 (#1893) Fix transaction ordering for ETH txns
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
  vendor/github.com/nanmu42/etherscan-api/account.go
Labels: ethereum, 🔍 readyForReview

#1901 Fix transports for message retriever and images
  core/images.go
  net/retriever/retriever.go
Labels: ordering, 🔍 readyForReview

#1909 (#1907) Check for empty peer ID before adding to spendResponse
  core/images.go
  core/spend.go
  net/retriever/retriever.go
  net/service/handlers.go
Labels: bug, ordering, 🔍 readyForReview

#1896 (#1815) Add currency value to refundAddressTransaction
  core/refunds.go
Labels: ethereum, 🔍 readyForReview

#1913 [#1879] Ensure PATCH /ob/profile returns appropriate response
  api/jsonapi_test.go
  core/profile.go
  repo/listing.go
  repo/profile.go
Labels: ethereum, 🚧 in progress

#1890 (#1846) Unable to load legacy orders due to payment coin refactor
  core/order.go
  repo/db/purchases.go
Labels: :rocket: :no_entry_sign:, bug, discussion, ethereum, 🔍 readyForReview

#1925 (#1861, 1862) Update vendored transports for Master
  core/images.go
  net/retriever/retriever.go
  vendor/github.com/OpenBazaar/multiwallet/bitcoincash/exchange_rates.go
  vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
  vendor/github.com/OpenBazaar/multiwallet/litecoin/exchange_rates.go
  vendor/github.com/OpenBazaar/multiwallet/zcash/exchange_rates.go
Labels: 🔍 readyForReview

#1910 (#1892) QA Runner
  Dockerfile.dev
  Dockerfile.qa
  Makefile
  qa/runtests.sh
Labels: needs review, 🔍 readyForReview

#1934 Do not mark wallet address as watched + fix earlier txn errors
  vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go
Labels: 🔍 readyForReview

#1935 Rebase of #1611 Improve config errors
  schema/configuration.go
Labels: ethereum, 🔍 readyForReview

#1927 Merge v0.13.7 hotfix
  core/core.go
  docs/install-linux.md
  docs/install-osx.md
  docs/install-pi3.md
  docs/install-windows.md
  package.json
  vendor/github.com/OpenBazaar/multiwallet/zcash/sign.go
Labels: ordering, 🔍 readyForReview

#1920 (#1919) Migrate to AddWatchedAddresses
  core/images.go
  core/order.go
  net/retriever/retriever.go
  net/service/handlers.go
  repo/db/watched_scripts.go
  vendor/github.com/OpenBazaar/bitcoind-wallet/wallet.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/erc20_wallet.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
  vendor/github.com/OpenBazaar/multiwallet/client/pool.go
  vendor/github.com/OpenBazaar/multiwallet/datastore/mock.go
  vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/model/interfaces.go
  vendor/github.com/OpenBazaar/multiwallet/service/wallet_service.go
  vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
  vendor/github.com/OpenBazaar/spvwallet/wallet.go
  vendor/github.com/OpenBazaar/wallet-interface/datastore.go
  vendor/github.com/OpenBazaar/wallet-interface/wallet.go
  vendor/github.com/OpenBazaar/zcashd-wallet/wallet.go
  wallet/resync/resync_manager.go
Labels: needs review, ordering, 🔍 readyForReview
