Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-05, with the labels that each got.

#1549 Increase chat timestamp resolution
  repo/db/chat.go
  repo/db/chat_test.go
  repo/init.go
  repo/migration.go
  repo/migrations/Migration015.go
  repo/migrations/Migration017.go
  repo/migrations/Migration018.go
  repo/migrations/Migration019.go
  repo/migrations/Migration021.go
  repo/migrations/Migration023.go
  repo/migrations/Migration023_test.go
Labels: client dependent, enhancement

#1543 Use go-emoji to convert to html chars
  core/core.go
  core/core_test.go
Labels: enhancement

#1608 Fix timestamp shift migration from being reapplied over and over
  repo/migrations/Migration023.go
  repo/migrations/Migration023_test.go
Labels: bug
