Repository OpenBazaar/openbazaar-go, pull requests merged in 2019-11, with the labels that each got.

#1830 (#1801) Fix surcharge parsing error on purchase
  core/order.go
  core/order_test.go
  repo/db/purchases_test.go
  repo/db/sales_test.go
  repo/db/util.go
  repo/listing.go
Labels: ethereum, 🚧 in progress

#1829 (#1810) Correctly set coinType db return only when CryptoListing
  repo/db/cases.go
  repo/db/cases_test.go
  repo/db/purchases.go
  repo/db/purchases_test.go
  repo/db/sales.go
  repo/db/sales_test.go
Labels: ethereum, 🔍 readyForReview

#1845 (#1572) Record aging improvements
  core/record_aging_notifier.go
  core/utils.go
  repo/db/cases.go
  repo/db/chat.go
  repo/db/coupons.go
  repo/db/db.go
  repo/db/followers.go
  repo/db/following.go
  repo/db/inventory.go
  repo/db/keys.go
  repo/db/messages.go
  repo/db/moderatedstores.go
  repo/db/notifications.go
  repo/db/offinemessages.go
  repo/db/pointers.go
  repo/db/purchases.go
  repo/db/sales.go
  repo/db/settings.go
  repo/db/stxo.go
  repo/db/txmetadata.go
  repo/db/txns.go
  repo/db/utxos.go
  repo/db/watched_scripts.go
Labels: ethereum, 🔍 readyForReview

#1843 (#1836) Only validate divisibility in sales listener if not crypto listing
  wallet/listeners/transaction_listener.go
Labels: ethereum, 🔍 readyForReview

#1849 (#1835) Fix cryptolisting price calculation for ETH payments
  core/order.go
Labels: 🔍 readyForReview

#1852 (#1844) Allow crypto currency listings with quantity of zero
  api/jsonapi_test.go
  repo/listing.go
Labels: ethereum

#1806 (#1718, #1721) Create Migration027 and update Migration028
  repo/migrations/Migration027.go
  repo/migrations/Migration027_test.go
  repo/migrations/Migration028.go
  repo/migrations/Migration028_test.go
Labels: :rocket: :no_entry_sign:, ethereum, internal, 🔍 readyForReview

#1817 (#1797) Inbound msg persistence
  cmd/start.go
  core/core.go
  core/inbound_message_scanner.go
  core/inbound_message_scanner_test.go
  core/net.go
  net/service/handlers.go
  openbazaard.go
  qa/eth_escrow_release_after_timeout.py
  repo/datastore.go
  repo/db/messages.go
  repo/db/messages_test.go
  repo/db/purchases_test.go
  repo/migrations/Migration032.go
  repo/migrations/Migration032_test.go
  repo/models.go
  schema/constants.go
  test/factory/message.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
  vendor/github.com/OpenBazaar/wallet-interface/wallet.go
Labels: :rocket: :no_entry_sign:, ethereum, 🔍 readyForReview

#1858 (#1839) Validate moderator fee schedule
  api/jsonapi_test.go
  core/moderation.go
  core/profile.go
  repo/currency.go
  repo/currency_test.go
  repo/dispute_resolution.go
  repo/dispute_resolution_test.go
  repo/profile.go
  repo/profile_test.go
  test/factory/currency.go
  test/factory/profile.go
Labels: :rocket: :no_entry_sign:, bug, ethereum, 🔍 readyForReview

#1857 Fix the eth qa tests
  core/disputes.go
  net/service/handlers.go
  qa/eth_cancel_direct_offline.py
  qa/eth_complete_moderated_online.py
  qa/eth_purchase_direct_online.py
  qa/eth_reject_moderated_offline.py
  qa/manage_crypto_listings.py
  qa/purchase_crypto_listing.py
  qa/purchase_direct_online.py
  qa/testdata/eth_digital.json
  qa/testdata/eth_listing.json
  qa/testdata/listing.json
  qa/testdata/listing_crypto.json
  qa/upload_listing.py
  repo/listing.go
Labels: ethereum, 🔍 readyForReview

#1873 (#1809) Set payment notification fundingTotal to CurrencyValue
  repo/notification.go
  wallet/listeners/transaction_listener.go
Labels: ethereum, 🔍 readyForReview

#1872 (#1834) Do not allow purchases if amount is lower than the wallet's dust amount
  core/order.go
Labels: ethereum, 🔍 readyForReview

#1869 (#1868) Add Migration033 to node migration list
  repo/init.go
  repo/migration.go
Labels: bug, ethereum, 🔍 readyForReview

#1874 Add date to the timestamps in Haven logging
  mobile/node.go
Labels: feature, 🔍 readyForReview

#1876 Fix formatted logging messages
  net/retriever/retriever.go
Labels: bug

#1871 OS X Ulimit Error Fix
  core/ulimit_unix.go
Labels: bug
