Repository OpenBazaar/openbazaar-go, pull requests merged in 2020-03, with the labels that each got.

#2011 Exponential Backoffs for Socket Connection to Blockbook
  vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
  vendor/github.com/cenkalti/backoff/LICENSE
  vendor/github.com/cenkalti/backoff/README.md
  vendor/github.com/cenkalti/backoff/backoff.go
  vendor/github.com/cenkalti/backoff/backoff_test.go
  vendor/github.com/cenkalti/backoff/context.go
  vendor/github.com/cenkalti/backoff/context_test.go
  vendor/github.com/cenkalti/backoff/example_test.go
  vendor/github.com/cenkalti/backoff/exponential.go
  vendor/github.com/cenkalti/backoff/exponential_test.go
  vendor/github.com/cenkalti/backoff/go.mod
  vendor/github.com/cenkalti/backoff/retry.go
  vendor/github.com/cenkalti/backoff/retry_test.go
  vendor/github.com/cenkalti/backoff/ticker.go
  vendor/github.com/cenkalti/backoff/ticker_test.go
  vendor/github.com/cenkalti/backoff/timer.go
  vendor/github.com/cenkalti/backoff/tries.go
  vendor/github.com/cenkalti/backoff/tries_test.go
Labels: 🔍 readyForReview

#2013 Values from DB that get reflected into scientific notation are kept as strings
  repo/db/sales.go
Labels: bug, ethereum, 🔍 readyForReview

#2014 feat: Save outbound order payment, refund, and dispute messages
  core/disputes.go
  core/net.go
Labels: ethereum, 🔍 readyForReview

#2015 Return no confirmations if endpoint is not aware of the tx
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: bug, ethereum, 🔍 readyForReview

#2019 Fix eth wallet websocket update height
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: bug, 🔍 readyForReview

#2016 (#2003) Fix bug returning coupon discount code for own node
  repo/listing.go
Labels: ethereum, 🔍 readyForReview

#2017 (#2007) Fix eth GetConfirmations height
  repo/db/sales.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: ethereum, 🔍 readyForReview

#2020 (#1943) Fix currency value in order notification
  repo/listing.go
  wallet/listeners/transaction_listener.go
Labels: ethereum, 🔍 readyForReview

#2030 Check for nil blocknumber when retrieving tx
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: bug

#2031 Changed ReleaseFunds func to check if transaction goes through before saving
  core/disputes.go
Labels: ordering

#2032 feat: Endpoint to hash a message
  api/endpoints.go
  api/jsonapi.go
Labels: feature

#2034 Save and load unconfirmed txs from db
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: ethereum, 🚧 in progress
