Repository OpenBazaar/openbazaar-go, pull requests merged in 2020-01, with the labels that each got.

#1940 [#1681] Protect POSTReleaseEscrow sweep when there are no inputs
  core/completion.go
Labels: ordering, 🔍 readyForReview

#1947 Add version to profile protobuf
  core/profile.go
  pb/profile.pb.go
  pb/protos/profile.proto
Labels: 🔍 readyForReview

#1939 (#1938) Improve Offline Message Debugging Log
  net/retriever/retriever.go
Labels: ethereum, feature, ordering, refactoring

#1961 [#1960] Gracefully continue past GetTransactions and GetUtxos errors
  Godeps/Godeps.json
  vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
  vendor/github.com/OpenBazaar/multiwallet/litecoin/address/address.go
Labels: bug

#1964 Send addresses as slice to BlockBook
  Godeps/Godeps.json
  vendor/github.com/OpenBazaar/multiwallet/client/blockbook/client.go
Labels: BlockBook, bug

#1915 (#1783) Make ETH transactions asynchronous
  qa/eth_cancel_direct_offline.py
  qa/eth_complete_direct_online.py
  qa/eth_dispute_close_buyer.py
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/client.go
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: :rocket: :no_entry_sign:, ethereum, 🔍 readyForReview

#1970 (#1803) Fix double negative bug in refundAddressTransaction
  core/utils.go
Labels: ethereum, 🔍 readyForReview
