Repository OpenBazaar/openbazaar-go, pull requests merged in 2020-02, with the labels that each got.

#1973 Include currency definition in sales, purchases, and cases db models
  core/disputes.go
  repo/db/cases.go
  repo/db/cases_test.go
  repo/db/purchases.go
  repo/db/purchases_test.go
  repo/db/sales.go
  repo/db/sales_test.go
  repo/db/util.go
  repo/models.go
Labels: 🔍 readyForReview

#1975 Fix failing signature validation
  Godeps/Godeps.json
  core/order.go
  repo/listing.go
  repo/signed_listing.go
  repo/signed_listing_test.go
  vendor/github.com/gorilla/websocket/.travis.yml
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/go.mod
  vendor/github.com/gorilla/websocket/go.sum
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
Labels: ethereum, 🔍 readyForReview

#1974 Support legacy profiles
  core/profile.go
  repo/currency.go
  repo/currency_test.go
  repo/profile.go
  repo/profile_test.go
  test/factory/fixtures/profiles/v0-profile-moderator-fixed-fee.json
  test/factory/fixtures/profiles/v4-profile-moderator-fixed-fee.json
  test/factory/fixtures/profiles/v5-profile-moderator-fixed-fee.json
  test/factory/helper.go
  test/factory/listing.go
  test/factory/profile.go
Labels: bug, ethereum, 🔍 readyForReview

#1979 Fix failing QA test due to dust amount
  Godeps/Godeps.json
  qa/eth_purchase_crypto_listing.py
  qa/purchase_crypto_listing.py
  qa/runtests.sh
  qa/runtests_eth.sh
  qa/testdata/eth_listing_crypto.json
  qa/testdata/listing_crypto.json
  qa/testdata/order_crypto.json
  qa/testdata/order_direct_too_much_quantity.json
  vendor/github.com/OpenBazaar/multiwallet/bitcoin/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/bitcoincash/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/litecoin/wallet.go
  vendor/github.com/OpenBazaar/multiwallet/zcash/wallet.go
  vendor/github.com/OpenBazaar/spvwallet/.travis.yml
  vendor/github.com/OpenBazaar/spvwallet/Dockerfile.dev
  vendor/github.com/OpenBazaar/spvwallet/Gopkg.lock
  vendor/github.com/OpenBazaar/spvwallet/docker-compose.yml
  vendor/github.com/OpenBazaar/spvwallet/sortsignsend.go
  vendor/github.com/OpenBazaar/spvwallet/wallet.go
Labels: :rocket: :no_entry_sign:, bug

#1980 (#1976) Normalize legacy listings via GET /ob/listings/...
  api/jsonapi.go
  core/order.go
  repo/db/sales.go
  repo/listing.go
  repo/listing_test.go
  repo/signed_listing.go
  repo/signed_listing_test.go
Labels: :rocket: :no_entry_sign:, ethereum, feature

#1985 Fix transaction ordering and enable Tor flag for the qa script
  Godeps/Godeps.json
  qa/eth_escrow_release_after_timeout.py
  qa/test_framework/test_framework.py
  qa/testdata/eth_listing.json
  vendor/github.com/OpenBazaar/go-ethwallet/wallet/wallet.go
Labels: ethereum, 🔍 readyForReview

#1990 (*repo.CurrencyValue).ConvertTo accepts a *repo.CurrencyConverter
  cmd/start.go
  core/moderation.go
  core/order.go
  core/order_test.go
  core/utils.go
  mobile/node.go
  repo/currency.go
  repo/currency_converter.go
  repo/currency_test.go
  test/factory/currency_converter.go
Labels: internal, refactoring

#1995 (#1983) Calculate order total w normalized listings
  core/order.go
  core/order_test.go
  repo/currency.go
  repo/currency_test.go
Labels: feature, internal

#2001 [#1983] Support testnet reserve currency converter usage
  core/order.go
  qa/test_framework/test_framework.py
  repo/currency_converter.go
Labels: bug
